server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/dannyhenian/{application}
#          uri: https://gitee.com/dannyhenian/config-repo-danny  # 公用
#          clone-on-start: true
#          username:
#          password:
#          repos:
#            simple: https://git.oschina.net/it-much/simple
#            special:
#              pattern: special*/dev*,special*/test*
#              uri: https://git.oschina.net/it-much/special
#          search-paths:
#            - foo   # foo路径
#            - bar   # bar路径
