spring:
  application:
    name: microservice-gateway-zuul
server:
  port: 8040
eureka:
  instance:
    ip-address: 192.168.2.119
    hostname: server1
    prefer-ip-address: true # true为不使用主机名来定义注册中心的地址，而使用IP地址的形式，而defaultZone中是以域名的方式向注册中心注册的
#    prefer-ip-address: false # true为不使用主机名来定义注册中心的地址，而使用IP地址的形式，而defaultZone中是以域名的方式向注册中心注册的
    instance-id: ${eureka.instance.ip-address}:${server.port}
#    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    healthcheck:       # 需要引入spring-boot-starter-actuator
      enabled: true
    serviceUrl:
#      defaultZone: http://server1:8761/eureka/,http://server2:8762/eureka/,http://server3:8763/eureka/
#      defaultZone: http://user:password123@server1:8761/eureka
      defaultZone: http://user:password123@localhost:8761/eureka
#  instance:
#    prefer-ip-address: true
zuul:
  routes:
    abc:
      path: /user-url/**
      service-id: microservice-provider-user
#ribbon:
#  eureka:
#    enabled: false
#microservice-provider-user:     # 这边是ribbon要请求的微服务的serviceId
#  ribbon:
#    listOfServers: http://localhost:7900
#    listOfServers: http://localhost:7900,http://localhost:7901