server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/dannyhenian/config-repo-danny
          username: 447579568@qq.com
          password: abc447579568
          
encrypt:
  key: foo