#http://blog.csdn.net/liuchuanhong1/article/details/54895070
spring:
  application:
    name: EUREKA-HA
  profiles:
    active: register1
#  security:
#    user:
#      name: user
#      password: password123