server:
  port: 8761

#spring:
#  security:
#    user:
#      name: user
#      password: password123

eureka:
  instance:
    ip-address: 192.168.2.119
#    hostname: server1
#    prefer-ip-address: true # true为不使用主机名来定义注册中心的地址，而使用IP地址的形式，而defaultZone中是以域名的方式向注册中心注册的
    prefer-ip-address: false # true为不使用主机名来定义注册中心的地址，而使用IP地址的形式，而defaultZone中是以域名的方式向注册中心注册的
#    instance-id: ${eureka.instance.ip-address}:${server.port}
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    fetch-registry: true        #一定要设置为true或者不写，否则会出现unavailable-replicas
    register-with-eureka: true  #一定要设置为true或者不写，否则会出现unavailable-replicas
    serviceUrl:
#      defaultZone: http://192.168.2.119:8762/eureka/,http://192.168.2.119:8763/eureka/
#      defaultZone: http://user:password123@server1:8761/eureka/,http://user:password123@server2:8762/eureka/,http://user:password123@server3:8763/eureka/
      defaultZone: http://server2:8762/eureka/,http://server3:8763/eureka/
#      defaultZone: http://user:password123@server2:8762/eureka
#      defaultZone: http://user:password123@server2:8762/eureka,http://user:password123@server3:8763/eureka
    registry-fetch-interval-seconds: 30
  server:
    enable-self-preservation: false #关闭自我保护机制