server:
  port: 8080
#  ssl:
#    key-store:


management:
  security:
    enabled: false

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test #jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF8&useSSL=false
    username: root
    password: root
    druid:                     # 连接池配置,初始化大小，最小，最大
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/test
#      username: root
#      password: root
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000          # 配置获取连接等待超时的时间
      time-between-eviction-runs-millis: 60000     # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000     # 配置一个连接在池中最小生存的时间，单位是毫秒
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      validation-query: SELECT 1 FROM DUAL
      pool-prepared-statements: true              # 打开PSCache，并且指定每个连接上PSCache的大小
      max-pool-prepared-statement-per-connection-size: 20
      filter: stat,wall,log4j        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000     # 通过connectProperties属性来打开mergeSql功能；慢SQL记录

mybatis:
  type-aliases-package: com.danny.cloud.entity          #实体类包路径
  mapper-locations: classpath:mapper/*.xml
mapper:
  mappers: com.danny.cloud.util.MyMapper  #mappers 多个接口时逗号隔开
  not-empty: false   #insert、update是否判断字符串类型!='' 即 test="str != null"表达式内是否追加 and str != ''
  identity: MYSQL
pagehelper:
  helper-dialect: mysql
  reasonable: true                  #页码<=0 查询第一页，页码>=总页数查询最后一页
  support-methods-arguments: true   #支持通过 Mapper 接口参数来传递分页参数
  params: count=countSql
  page-size-zero: true                  #分页尺寸为0时查询所有纪录不再执行分页











