spring:
  application:
    name: microservice-consumer-movie-ribbon-properties-customizing
server:
  port: 8010
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
microservice-provider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#  ConnectTimeOut: 250               #请求连接的超时时间
#  ReadTimeOut: 1000                 #请求处理得超时时间
#  OkToRetryOnAllOperations: true    #对所有操作请求都进行重试
#  MaxAutoRetriesNextServer: 2       #切换实例的重试次数
#  MaxAutoRetries: 1                 #对当前实例的重试次数