server:
  port: 8091                          #指定该eureka实例的端口
eureka:
  client:
    register-with-eureka: false           #是否注册到其他eureka实例
    fetch-registry: false                 #是否合并其他eureka实例上的数据
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/    #默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔

