#security:
#  basic:
#    enabled: true    #开启密码验证需引入spring-boot-starter-security
#  user:
#    name: user
#    password: password123

spring:
  application:
    name: eureka-server
  security:
    user:
      name: user
      password: password123
server:
  port: 8761
eureka:
  instance:
    ip-address: 192.168.2.119
#    hostname: server1
    prefer-ip-address: true # true为不使用主机名来定义注册中心的地址，而使用IP地址的形式，而defaultZone中是以域名的方式向注册中心注册的
#    prefer-ip-address: false # true为不使用主机名来定义注册中心的地址，而使用IP地址的形式，而defaultZone中是以域名的方式向注册中心注册的
    instance-id: ${eureka.instance.ip-address}:${server.port}
#    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
#      defaultZone: http://user:password123@server1:8761/eureka
